### ISSUE TITLE
是否能尝试一下兼容Node.

### ISSUE THREAD

**Issue by w88975** [gridjs/gridjs#4]
很早之前看到这个库,只是觉得这个库仅仅用来学习用,但是最近又看到,想着用浏览器端的API来处理图片,其实有时候并不太理想.

而突发奇想,如果能够改成一个Node模块,那是否是一个非常好的选择,实用性大大提高.虽然可能重复造轮子,但是不妨可以尝试一下。
（Node中处理图片的一些库,对于许多图像处理的lib的依赖太严重,如果能用纯JS去处理，那岂不是更好?虽然效率上可能会差一点。）

如果作者有兴趣,我愿意协助一起来开发一个Node版的Grid-JS.

**Comment by Sneezry** [comment]
Hi @w88975 ，node版听起来很让人兴奋，不过gridjs在图像处理上是基于canvas的，node好像没有dom，所以这个支持起来似乎不是太容易，不知道你有没有什么更好的想法呢 :-D

**Comment by w88975** [comment]
我有看过你的代码, 其实你是通过canvas的getImageData来获取图片的像素点集合,通过操作像素来实现filter,其实如果想移植到Node,只需要在Node里把canvas取出imageData的那部分代码换成Node去操作。

**Comment by w88975** [comment]
例如:
- https://github.com/scijs/get-pixels

**Comment by yy1107** [comment]
我觉得对我一个没文化的日来说太难了要是可以你们帮我做好了，看到你们那么强大佩服啊，

**Comment by Sneezry** [comment]
@yy1107 please stop making spam
